name: Metrics

on:
  schedule: [{ cron: "0 */6 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: tonysatrem
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Moscow
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # plugin_languages: yes
          # plugin_languages_colors: github
          # plugin_languages_details: lines, percentage
          # plugin_languages_indepth: yes
          # plugin_languages_limit: 0
          # plugin_languages_recent_days: 0
          # plugin_languages_recent_load: 1000
          # plugin_languages_sections: most-used, recently-used
          # plugin_languages_threshold: 0%
          # plugin_languages_analysis_timeout: 60
          # plugin_languages_analysis_timeout_repositories: 0
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          commits_authoring: Tony Satrem, tonysatrem
